### ISSUE TITLE
"failed to parse JSON" error

### ISSUE THREAD

**Issue by extsoft** [yegor256/wring#34]
I registered my own pipe and have the following messages in my inbox:
```
failed to parse JSON:
{
  "class": "io.wring.agents.github.AgGithub",
  "token": "my-tocken-here"
}

java.lang.IllegalArgumentException: event with title "io.wring.agents.github.AgGithub by 0.14.1" not found
	at io.wring.dynamo.DyEvents.event(DyEvents.java:161)
	at io.wring.agents.IgnoreEvents.event(IgnoreEvents.java:112)
	at io.wring.agents.BoostEvents.post(BoostEvents.java:102)
	at io.wring.agents.Exec.run(Exec.java:106)
	at io.wring.agents.Cycle.process(Cycle.java:107)
	at io.wring.agents.Cycle.run(Cycle.java:77)
	at com.jcabi.log.VerboseRunnable.run(VerboseRunnable.java:198)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at com.jcabi.log.VerboseThreads$Wrap.run(VerboseThreads.java:220)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@extsoft can you please make a screenshot? I can't understand where exactly you see this

**Comment by extsoft** [comment]
> 

@yegor256 Main page - http://www.wring.io. 
![capto_capture 2017-05-30_22-26-26_](https://cloud.githubusercontent.com/assets/5806627/26601434/714598ae-4588-11e7-857a-154fa379451d.png)

**Comment by yegor256** [comment]
@rultor release, tag is `0.14.2`

**Comment by yegor256** [comment]
@rultor release, tag is `0.14.2`

**Comment by yegor256** [comment]
@extsoft please, try again. You most probably will see an error, but a different one.

**Comment by extsoft** [comment]
@yegor256 I looked for Wring's behavior for a while. There are 0 messages in the inbox. Look's like Wring doesn't show or retrieve notifications. How are we able to determine root cause?

**Comment by yegor256** [comment]
@extsoft just nothing? Not even error messages?

**Comment by extsoft** [comment]
@yegor256 Yes, just nothing.

**Comment by yegor256** [comment]
@extsoft what is your GitHub user id? It's a number.

**Comment by extsoft** [comment]
@yegor256 `5806627` from [https://caius.github.io/github_id/#extsoft]()

**Comment by yegor256** [comment]
@extsoft are you sure you registered a pipe? I don't see any errors in the log. It seems that the server is just not doing anything with your account.

**Comment by extsoft** [comment]
@yegor256 Yes, I have the pipe #1501659400232

**Comment by yegor256** [comment]
@extsoft I will implement additional tracking/logging feature in #41 and we'll see

**Comment by yegor256** [comment]
@extsoft also, please check that your "web notifications" are turned on in GitHub:

<img width="1003" alt="screen shot 2017-08-06 at 11 59 03 am" src="https://user-images.githubusercontent.com/526301/29001917-b614ce82-7a9e-11e7-8d2a-7f391af68186.png">

**Comment by extsoft** [comment]
@yegor256 they are on. 
<img width="1043" alt="screen shot 2017-08-06 at 12 00 50" src="https://user-images.githubusercontent.com/5806627/29001928-f92d2bba-7a9e-11e7-82b0-44143d835bbd.png">

**Comment by yegor256** [comment]
@extsoft try your "pipes" page now. You should see the status line next to the pipe number. What does it say?

**Comment by extsoft** [comment]
@yegor256 My notifications:
<img width="1018" alt="screen shot 2017-08-07 at 12 58 37" src="https://user-images.githubusercontent.com/5806627/29022065-76e24348-7b70-11e7-92e9-5a4e64845eb0.png">
Pipe status: 
<img width="601" alt="screen shot 2017-08-07 at 12 59 56" src="https://user-images.githubusercontent.com/5806627/29022073-7c990344-7b70-11e7-8927-4d34777d7609.png">
**Inbox is empty.** 

And looks like Wring marks all github notifications as they were read.

**Comment by yegor256** [comment]
@extsoft maybe wring just filters everything out? Can you show me your pipe JSON config? Remove the authentication code.

**Comment by extsoft** [comment]
@yegor256 `{"class": "io.wring.agents.github.AgGithub","token": "xxxxxxxxxx"}`

**Comment by yegor256** [comment]
@extsoft can you please make a screenshot of your inbox?

**Comment by extsoft** [comment]
@yegor256 
<img width="985" alt="screen shot 2017-08-08 at 11 51 51" src="https://user-images.githubusercontent.com/5806627/29063941-12dbd506-7c30-11e7-9c28-b02dddfcc946.png">

**Comment by yegor256** [comment]
@extsoft it's a mistery :)

**Comment by extsoft** [comment]
@yegor256, any ideas how we can find a root cause? 
The use case I saw:
- have a new notification
- open `pipes` and see `1 event for ...`
- open `inbox` and see zero messages
- back to `pipes` and see `0 events for ...`
May this will help.

**Comment by yegor256** [comment]
@extsoft let me investigate. It's a damn mystery, but we have to solve it :)

**Comment by yegor256** [comment]
@rultor release, tag is `0.17.1`

**Comment by yegor256** [comment]
@extsoft what do you see now?

**Comment by yegor256** [comment]
@rultor release, tag is `0.17.2`

**Comment by extsoft** [comment]
> @extsoft what do you see now?

@yegor256 I see 4 messages in the inbox. Wring works! But let I take a look for a while.

**Comment by yegor256** [comment]
@extsoft it was a bug, thanks for reporting it! You can close this ticket and open a new one if you see any more bugs.

**Comment by extsoft** [comment]
@yegor256 thank you for fixing the bug.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/wring#34` was not in scope
