### ISSUE TITLE
Broken link to a badge on the index page

### ISSUE THREAD

**Issue by php-coder** [yegor256/wring#45]
On the index page (http://www.wring.io/) I see a broken image. The badge has a link to http://www.zerocracy.com/badge.svg that leads to 404

**Comment by filfreire** [comment]
@yegor256 this issue is still valid. It seems the commit that could solve this, https://github.com/yegor256/wring/commit/89fc1a24b3817f8b6392bd6db032cf5f8123d588, was never tagged for release and deployed.

**Comment by yegor256** [comment]
@rultor release, tag is `0.17.5`

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
