### ISSUE TITLE
HTTPS is not supported

### ISSUE THREAD

**Issue by g4s8** [yegor256/wring#46]
Encryption is critical for this kind of applications which use API tokens and can receive notifications from private repositories on Github. Without it any script kiddie connected to your wifi will be able to get access to your Github account via API or read your messages.

**Comment by 0crat** [comment]
The job [#46](https://github.com/yegor256/wring/issues/46) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/C7FCB1EQN/681214684). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 points just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@g4s8 I believe it's fixed. The DNS will update in about a day and the warning will disappear.

**Comment by yegor256** [comment]
@rultor release, tag is `0.18`

**Comment by g4s8** [comment]
@yegor256 thanks!

**Comment by 0crat** [comment]
Order was finished: +30 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#46](https://github.com/yegor256/wring/issues/46) is now out of scope
