### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by g4s8** [yegor256/wring#49]
When I click login link, it redirects me on the same page, but with error in url parameters:
```https://www.wring.io/?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdeveloper.github.com%2Fapps%2Fmanaging-oauth-apps%2Ftroubleshooting-authorization-request-errors%2F%23redirect-uri-mismatch```

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@g4s8 fixed, thanks

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
