### ISSUE TITLE
wring.io doesn't load up in Firefox

### ISSUE THREAD

**Issue by peter-kehl** [yegor256/wring#64]
Accessing https://www.wring.io/ in Firefox 61.0.1 x32 on openSUSE x64 (this combination works well for other websites).  The page loads some artifacts and then hangs:

![image](https://user-images.githubusercontent.com/4270240/43673306-8dc7136e-9775-11e8-93a0-ff977623ab45.png)

It works in Chrome on the same machine.

**Comment by 0crat** [comment]
@carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) please, pay attention to this issue

**Comment by 0crat** [comment]
@peter-kehl[/z](https://www.0crat.com/u/peter-kehl) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C7FCB1EQN) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by peter-kehl** [comment]
@carlosmiranda  Ignore for now. That is because of my Firefox version. I'll follow up.

**Comment by peter-kehl** [comment]
Closing this ticket: not caused by Wring.

FYI The problem was caused by a Firefox Extension from https://www.i-dont-care-about-cookies.eu. It also halts www.rultor.com. The extension doesn't have a support/ticket system, hence I emailed the author.

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@f034b85b-35f1-4a3a-8859-7d98640626e8, thread: pool-39-thread-1
java.lang.NumberFormatException[65] java.lang.NumberFormatException: For input string: "2018-08-04T19:51:12.927Z"
```

[0.29.3](https://github.com/zerocracy/farm): Issue: yegor256/wring#64, Action: `closed`
