### ISSUE TITLE
Removing all pending notifications

### ISSUE THREAD

**Issue by peter-kehl** [yegor256/wring#65]
After adding a new pipe at www.wring.io, it seems to clear all pending notifications. That is not mentioned at https://www.wring.io/pipes nor at http://www.yegor256.com/2016/03/15/wring-dispatcher-github-notifications.html. Very user unfriendly.

I set up a pipe that I expected only to remove notifications matching `ignore` value. But all notifications disappeared.
```
{
  "class": "io.wring.agents.github.AgGithub",
  "token": "my-token",
  "ignore": "SeleniumHQ/selenium-ide"
}
```

Either document it, or better: make it not remove any pending notifications (meaning: Only apply the pipe to any new notifications since the pipeline creation).

**Comment by 0crat** [comment]
@carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) please, pay attention to this issue

**Comment by 0crat** [comment]
@peter-kehl[/z](https://www.0crat.com/u/peter-kehl) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C7FCB1EQN) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
@carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) everybody who has role `DEV` is banned at [#65](https://github.com/yegor256/wring/issues/65); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) everybody who has role `DEV` is banned at [#65](https://github.com/yegor256/wring/issues/65); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) everybody who has role `DEV` is banned at [#65](https://github.com/yegor256/wring/issues/65); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
The job [#65](https://github.com/yegor256/wring/issues/65) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/C7FCB1EQN/2360631321); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by paulodamaso** [comment]
@peter-kehl @carlosmiranda What about setting an date for `IgnoreEvents` and make it just work on events after this date?

**Comment by carlosmiranda** [comment]
@paulodamaso my understanding is @peter-kehl wants to NOT clear notifications that were pending before setting up the pipe. What's happening is it's only processing motifs created after. 

There might be a Github API limitation that's causing this, I'm not sure at the moment. Whatever the case let's either fix it or document the limitation.

**Comment by peter-kehl** [comment]
Hi Carlos and Paulo,

Confirming Carlos' understanding: NOT to clear notifications that were pending before setting up the pipe.

**Comment by paulodamaso** [comment]
@carlosmiranda @peter-kehl What I've found so far:
Github Agent `AgGithub` clears all notifications from Github after pushing them to database; it calls https://developer.github.com/v3/activity/notifications/#mark-notifications-as-read-in-a-repository , efectivelly marking all older notifications as `read`.  What we could do is to use https://developer.github.com/v3/activity/notifications/#list-your-notifications to iterate notifications manually (ignoring notifications before the pipe creation) and then iterate them manually and mark it as read with https://developer.github.com/v3/activity/notifications/#mark-as-read endpoint .
This solves the problem, I think.

**Comment by peter-kehl** [comment]
@carlosmiranda and @paulodamaso, up to you to discuss/choose whether to have the change (how big could it be?), or to document the current behavior.

**Comment by carlosmiranda** [comment]
@paulodamaso sounds like a viable way to fix it, lets do it.

**Comment by paulodamaso** [comment]
@carlosmiranda I misunderstood the docs. We can't set notifications read one by one using the API, so I'm afraid that's impossible to do what @peter-kehl wants. I've added a line explaining this.

**Comment by paulodamaso** [comment]
@peter-kehl Merged, please close.

**Comment by paulodamaso** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/wring/issues/65#issuecomment-416791052))

@paulodamaso This is what I know about this job in [C7FCB1EQN](https://www.0crat.com/p/C7FCB1EQN), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#65](https://github.com/yegor256/wring/issues/65) is [in scope](http://www.zerocracy.com/policy.html#14) for 16days
  * The role is `DEV`
  * The job is assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) for [5days](http://www.zerocracy.com/policy.html#8)
  * There is a monetary reward attached
  * @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) will get 50% of their hourly rate for this job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @peter-kehl[/z](https://www.0crat.com/u/peter-kehl): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C7FCB1EQN?q=%7Bjob%3A%27gh%3Ayegor256%2Fwring%2365%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by paulodamaso** [comment]
@0crat out

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#65](https://github.com/yegor256/wring/issues/65) is now out of scope

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/yegor256/wring/issues/65#issuecomment-416796493))

@paulodamaso Job `gh:yegor256/wring#65` is not assigned, can't get performer

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/yegor256/wring/issues/65#issuecomment-416796493))

@paulodamaso The job is not in WBS, won't close the order

**Comment by ypshenychka** [comment]
@0crat quality good
