### ISSUE TITLE
Problem with encoding

### ISSUE THREAD

**Issue by alex-semenyuk** [yegor256/wring#67]
Got the following errors on test running:

`java.lang.IllegalStateException: Default encoding is windows-1251`

for TkAppTest.rendersAllPossibleUrls, TkAppTest.rendersHomePage, TkAppTest.rendersHomePageViaHttp tests

Encoding can be set explicitly set here

```
<plugin>
          <artifactId>maven-surefire-plugin</artifactId>
          <configuration>
            <argLine>-Duser.language=en -Duser.region=US -Djava.awt.headless=true **-Dfile.encoding=UTF-8**</argLine>
          </configuration>
</plugin>
```

**Comment by 0crat** [comment]
@carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) please, pay attention to this issue

**Comment by 0crat** [comment]
@alex-semenyuk[/z](https://www.0crat.com/u/alex-semenyuk) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C7FCB1EQN) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
Job [#67](https://github.com/yegor256/wring/issues/67) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @alex-semenyuk[/z](https://www.0crat.com/u/alex-semenyuk)

**Comment by 0crat** [comment]
The job [#67](https://github.com/yegor256/wring/issues/67) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/C7FCB1EQN/2471542852); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by paulodamaso** [comment]
@alex-semenyuk merged, please close

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +40 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
