### ISSUE TITLE
Exec.java:57-60: Errors occurred during execution must be...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/wring#76]
The puzzle `72-f572f084` from #72 has to be resolved: 

https://github.com/yegor256/wring/blob/220aed275459452f3c3a728eb3014e11b044a235/src/main/java/io/wring/agents/Exec.java#L57-L60

The puzzle was created by rultor on 26-Oct-18. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#76](https://github.com/yegor256/wring/issues/76) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#76](https://github.com/yegor256/wring/issues/76) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/C7FCB1EQN/e63979ea-ad92-4dab-a727-d0a2cc8a237e); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0pdd** [comment]
The puzzle `72-f572f084` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#85](https://github.com/yegor256/wring/issues/85), [#86](https://github.com/yegor256/wring/issues/86) are still not solved.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#76](https://github.com/yegor256/wring/issues/76) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good
