### ISSUE TITLE
TkErrors.java:57-58: Implement error deletion on errors...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/wring#82]
The puzzle `77-dabedd93` from #77 has to be resolved: 

https://github.com/yegor256/wring/blob/da98ac0ab57eb582453842c77e207f0be9105333/src/main/java/io/wring/tk/TkErrors.java#L57-L58

The puzzle was created by Paulo Lobo on 30-Oct-18. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#82](https://github.com/yegor256/wring/issues/82) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#82](https://github.com/yegor256/wring/issues/82) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/C7FCB1EQN/d8be1802-b715-46ec-af2d-aea0db988daf); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by paulodamaso** [comment]
@0crat wait for #84 review and merge

**Comment by 0crat** [comment]
> @0crat wait for #84 review and merge ([here](https://github.com/yegor256/wring/issues/82#issuecomment-436228408))

@paulodamaso The impediment for [#82](https://github.com/yegor256/wring/issues/82) was registered successfully by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0pdd** [comment]
The puzzle `77-dabedd93` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#82](https://github.com/yegor256/wring/issues/82) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
> @0crat quality good ([here](https://github.com/yegor256/wring/issues/82#issuecomment-446674056))

@ypshenychka The project doesn't have enough funds, can't make a payment

**Comment by 0crat** [comment]
> @0crat quality good ([here](https://github.com/yegor256/wring/issues/82#issuecomment-446674056))

@ypshenychka The project doesn't have enough funds, can't make a payment

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
