### ISSUE TITLE
DyErrors.java:52-54: Add errors table to dynamo. This...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/wring#83]
The puzzle `78-d3bf8dd1` from #78 has to be resolved: 

https://github.com/yegor256/wring/blob/16c98ad38556a42ca9353c81f19a0e51ca8e4b2e/src/main/java/io/wring/dynamo/DyErrors.java#L52-L54

The puzzle was created by Paulo Lobo on 27-Oct-18. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#83](https://github.com/yegor256/wring/issues/83) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#83](https://github.com/yegor256/wring/issues/83) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/C7FCB1EQN/c9da230a-2987-479c-b138-0875414c0241); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by paulodamaso** [comment]
@carlosmiranda please take e look at this, I couldn't find where to put the script to create this table.

**Comment by carlosmiranda** [comment]
@yegor256 need your help here

**Comment by paulodamaso** [comment]
@yegor256 please take a look at this

**Comment by paulodamaso** [comment]
@0crat wait for @yegor256 response

**Comment by 0crat** [comment]
> @0crat wait for @yegor256 response ([here](https://github.com/yegor256/wring/issues/83#issuecomment-436228971))

@paulodamaso The impediment for [#83](https://github.com/yegor256/wring/issues/83) was registered successfully by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by yegor256** [comment]
@paulodamaso thanks!

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#83](https://github.com/yegor256/wring/issues/83) is now out of scope

**Comment by ypshenychka** [comment]
@paulodamaso According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>Ticket must have references to all pull requests where the problem was actually fixed;

Please add reference to PR.

**Comment by ypshenychka** [comment]
@paulodamaso So was it not possible to create PR for that?

**Comment by paulodamaso** [comment]
@yegor256 what's the status on this one? Have you created the table sou I can made a PR for this one?

**Comment by paulodamaso** [comment]
@yegor256 ping

**Comment by paulodamaso** [comment]
@carlosmiranda Looks like something went wrong here, @yegor256 closed the issue but we do not know if he created the table that I need to uncomment and  fix the tests

**Comment by paulodamaso** [comment]
@yegor256 These are the table specs:
```
{
    "AttributeDefinitions": [
        {
            "AttributeName": "urn",
            "AttributeType": "S"
        },
        {
            "AttributeName": "title",
            "AttributeType": "S"
        },
        {
            "AttributeName": "description",
            "AttributeType": "S"
        },
        {
            "AttributeName": "time",
            "AttributeType": "N"
        }
    ]
    "TableName": "errors"
}

```

**Comment by ypshenychka** [comment]
@yegor256 Any progress with this one? It's hanging as closed in my agenda for more than a month, but stilll some work is going around.

**Comment by yegor256** [comment]
@paulodamaso what about keys? Can you put this table into JSON format, where all other tables are?

**Comment by paulodamaso** [comment]
@yegor256 please take a look at https://github.com/yegor256/wring/pull/89

**Comment by paulodamaso** [comment]
@yegor256 ping

**Comment by ypshenychka** [comment]
@paulodamaso Looks like PR is merged. Please proceed with closing this ticket then.

**Comment by paulodamaso** [comment]
@ypshenychka The ticket is already closed and was remoed from scope in https://github.com/yegor256/wring/issues/83#issuecomment-440917725 , but it was closed by mistake, without the proper resolution, which came only in https://github.com/yegor256/wring/pull/89 . So I think that you must make the QA revision of this issue

**Comment by ypshenychka** [comment]
@paulodamaso you're right. Thanks

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
> @0crat quality good ([here](https://github.com/yegor256/wring/issues/83#issuecomment-457230005))

@ypshenychka The project doesn't have enough funds, can't make a payment

**Comment by 0crat** [comment]
> @0crat quality good ([here](https://github.com/yegor256/wring/issues/83#issuecomment-457230005))

@ypshenychka The project doesn't have enough funds, can't make a payment

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
