### ISSUE TITLE
Wring does not fetch notifications

### ISSUE THREAD

**Issue by paulodamaso** [yegor256/wring#88]
I've set a `pipe` with the following configuration:
```
{
	"class": "io.wring.agents.github.AgGithub",
	"token":"<my-github-token>
}
```
This pipe was supposed to send all notifications to inbox, but I've received some notifications from github in my e-mail and none of them were sent to my inbox.

**Comment by 0crat** [comment]
@carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) please, pay attention to this issue

**Comment by yegor256** [comment]
@paulodamaso this was a temporary issue. Check now.

**Comment by 0crat** [comment]
Job `gh:yegor256/wring#88` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
