### ISSUE TITLE
I'm getting "connection timeout" for my inbox

### ISSUE THREAD

**Issue by yegor256** [yegor256/wring#91]
Something is not right.

**Comment by 0crat** [comment]
@carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) please, pay attention to this issue

**Comment by yegor256** [comment]
@carlosmiranda I'll fix it now

**Comment by yegor256** [comment]
@rultor release, tag is `0.19.11`

**Comment by 0crat** [comment]
Job `gh:yegor256/wring#91` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
